.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/custom.md, .github/PULL_REQUEST_TEMPLATE.md
- Issue & PR Template을 등록한다
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/PULL_REQUEST_TEMPLATE.md
Closes #1
=> [Docs] Issue & PR Template을 등록한다

src/main/java/umc/stockoneqback/board/domain/Board.java, src/main/java/umc/stockoneqback/board/domain/BoardRepository.java, src/main/java/umc/stockoneqback/comment/domain/Comment.java, src/main/java/umc/stockoneqback/comment/domain/CommentRepository.java, src/main/java/umc/stockoneqback/reply/domain/Reply.java, src/main/java/umc/stockoneqback/reply/domain/ReplyRepository.java, src/main/java/umc/stockoneqback/user/domain/User.java, src/test/java/umc/stockoneqback/board/domain/BoardTest.java, src/test/java/umc/stockoneqback/comment/domain/CommentTest.java, src/test/java/umc/stockoneqback/fixture/BoardFixture.java, src/test/java/umc/stockoneqback/fixture/CommentFixture.java, src/test/java/umc/stockoneqback/fixture/ReplyFixture.java, src/test/java/umc/stockoneqback/fixture/UserFixture.java, src/test/java/umc/stockoneqback/reply/domain/ReplyTest.java
게시글 및 댓글, 대댓글 엔티티를 생성한다
- Board Entity 
- Comment Entity
- Reply Entity
- TestCode
- BoardTest
- CommentTest
- ReplyTest 
첨부 파일은 일단 ERD를 참고해서 String으로 해서 작성 및 테스트 진행했습니다. 이 부분은 이후 첨부 파일 테이블이 따로 작성된다면 거기에 맞춰서 수정할 예정입니다.
확인하시고 피드백 부탁드립니다!
Closes #7
=> [Feat] 게시글 및 댓글, 대댓글 엔티티를 생성한다

src/main/java/umc/stockoneqback/auth/exception/AuthErrorCode.java, src/main/java/umc/stockoneqback/auth/utils/AuthorizationExtractor.java, src/main/java/umc/stockoneqback/auth/utils/JwtTokenProvider.java, src/main/java/umc/stockoneqback/business/controller/BusinessApiController.java, src/main/java/umc/stockoneqback/business/domain/Business.java, src/main/java/umc/stockoneqback/business/domain/BusinessRepository.java, src/main/java/umc/stockoneqback/business/exception/BusinessErrorCode.java, src/main/java/umc/stockoneqback/business/service/BusinessService.java, src/main/java/umc/stockoneqback/global/annotation/ExtractPayload.java, src/main/java/umc/stockoneqback/global/annotation/ExtractPayloadArgumentResolver.java, src/main/java/umc/stockoneqback/global/annotation/ExtractToken.java, src/main/java/umc/stockoneqback/global/annotation/ExtractTokenArgumentResolver.java, src/main/java/umc/stockoneqback/role/domain/store/Store.java, src/main/java/umc/stockoneqback/user/controller/UserApiController.java, src/main/java/umc/stockoneqback/user/exception/UserErrorCode.java, src/main/java/umc/stockoneqback/user/service/UserFindService.java, src/main/resources/application.yml, src/test/java/umc/stockoneqback/business/controller/BusinessApiControllerTest.java, src/test/java/umc/stockoneqback/business/domain/BusinessRepositoryTest.java, src/test/java/umc/stockoneqback/business/service/BusinessServiceTest.java, src/test/java/umc/stockoneqback/common/ControllerTest.java, src/test/java/umc/stockoneqback/common/ServiceTest.java, src/test/java/umc/stockoneqback/user/domain/UserRepositoryTest.java, src/test/resources/application.yml
- 슈퍼바이저의 사장님 연결 신청 API를 구현한다
- 슈퍼바이저 - 점장님 연결 신청/취소 API
- 테스트 코드 작성
- @ExtractPayload를 통해 토큰을 추출하여 사용자를 검증하는 테스트가 제대로 작동되지 않아 제외하였습니다. 이 부분은 인증/인가가 완료된 이후 추가로 수정해야할 것 같습니다. 죄송합니다.
Closes #25
=> 슈퍼바이저의 사장님 연결 신청 API를 구현한다

src/main/java/umc/stockoneqback/file/service/FileService.java, src/main/java/umc/stockoneqback/product/controller/ProductController.java, src/main/java/umc/stockoneqback/product/domain/Product.java, src/main/java/umc/stockoneqback/product/domain/ProductRepository.java, src/main/java/umc/stockoneqback/product/domain/StoreCondition.java, src/main/java/umc/stockoneqback/product/dto/request/EditProductRequest.java, src/main/java/umc/stockoneqback/product/dto/response/LoadProductResponse.java, src/main/java/umc/stockoneqback/product/dto/response/SearchProductResponse.java, src/main/java/umc/stockoneqback/product/dto/response/SearchProductUrl.java, src/main/java/umc/stockoneqback/product/exception/ProductErrorCode.java, src/main/java/umc/stockoneqback/product/service/ProductService.java
- 제품 생성/조회/수정/삭제 API를 구현한다
- 검색된 문자열을 포함하는 모든 제품을 리스트업하는 API를 구현한다
- 제품 추가
- 제품 상세정보 조회
- 제품 수정
- 제품 삭제
- 제품 검색
- StoreCondition을 확인해보시면 enum의 특정 value를 넣었을 때 해당하는 enum 값을 반환하면서 그렇지 않을 경우 exception이 뜨는 로직을 구현했으니 참고 부탁드립니다.
- 테스트 코드는 제품 목록 조회 API 구현이 완료된 시점에 모두 돌려보도록 하겠습니다😅
Closes #19
=> [Feat] 제품 생성/조회/수정/삭제 및 자동완성 조회 API를 구현한다

src/main/java/umc/stockoneqback/auth/config/WebConfig.java
- @ExtractPayload, @ExtractToken 어노테이션이 작동하지 않는 문제를 해결한다
- WebMvcConfigurer에 addArgumentResolvers 메소드 오버라이드 및 Resolver 등록
Closes #44
=> [Fix] @ExtractPayload, @ExtractToken 어노테이션이 작동하지 않는 문제를 해결한다

src/main/java/umc/stockoneqback/comment/controller/CommentApiController.java, src/main/java/umc/stockoneqback/reply/controller/ReplyApiController.java, src/test/java/umc/stockoneqback/board/controller/BoardApiControllerTest.java, src/test/java/umc/stockoneqback/comment/controller/CommentApiControllerTest.java, src/test/java/umc/stockoneqback/reply/controller/ReplyApiControllerTest.java
댓글, 대댓글 관련 코드 리팩토링을 진행한다
- 댓글, 대댓글 컨트롤러 writerId @PathVariable -> @ExtractPayload 로 수정
- BoardApiControllerTest 잘못된 에러 호출 수정
- 댓글 대댓글 ApiController 테스트코드 수정
Closes #53
=> [Refactor] 댓글, 대댓글 관련 코드 리팩토링을 진행한다

src/main/java/umc/stockoneqback/friend/controller/FriendFindApiController.java, src/main/java/umc/stockoneqback/friend/exception/FriendErrorCode.java, src/main/java/umc/stockoneqback/friend/service/FriendService.java, src/test/java/umc/stockoneqback/business/controller/BusinessApiControllerTest.java, src/test/java/umc/stockoneqback/common/ControllerTest.java, src/test/java/umc/stockoneqback/friend/controller/FriendApiControllerTest.java
- Friend Api Controller layer에 대한 테스트 코드를 작성한다
- FriendApiControllerTest 추가
- REFRESH_TOKEN으로 잘못 표기된 테스트를 ACCESS_TOKEN으로 수정
Closes #55
=> [Test] FriendApiController에 대한 테스트 코드를 작성한다

src/main/java/umc/stockoneqback/friend/controller/FriendFindApiController.java, src/main/java/umc/stockoneqback/friend/service/FriendFindService.java, src/main/java/umc/stockoneqback/friend/service/FriendService.java, src/main/java/umc/stockoneqback/user/domain/UserRepository.java, src/main/java/umc/stockoneqback/user/exception/UserErrorCode.java, src/test/java/umc/stockoneqback/common/ServiceTest.java, src/test/java/umc/stockoneqback/fixture/UserFixture.java, src/test/java/umc/stockoneqback/friend/service/FriendFindServiceTest.java, src/test/java/umc/stockoneqback/friend/service/FriendServiceTest.java
Friend 관련 테스트 코드를 작성한다
- FriendService 테스트코드 작성
- FriendFindService 리팩토링 및 테스트코드 작성
Closes #54
=> [Test] Friend 관련 테스트 코드를 작성한다

src/test/java/umc/stockoneqback/common/ServiceTest.java, src/test/java/umc/stockoneqback/file/service/FileServiceTest.java, src/test/java/umc/stockoneqback/friend/service/FriendFindServiceTest.java, src/test/java/umc/stockoneqback/friend/service/FriendServiceTest.java, src/test/java/umc/stockoneqback/product/controller/ProductApiControllerTest.java
- Merge 후 테스트가 돌아가지 않는 문제를 해결한다
- Merge 후 테스트가 돌아가지 않는 문제를 해결한다
Closes #74
=> [Fix] Merge 후 테스트가 돌아가지 않는 문제를 해결한다

src/main/java/umc/stockoneqback/global/config/WebConfig.java, src/main/java/umc/stockoneqback/global/security/SecurityConfig.java
=> feat: CORS

src/main/java/umc/stockoneqback/business/service/BusinessProductService.java, src/main/java/umc/stockoneqback/friend/service/FriendProductService.java, src/test/java/umc/stockoneqback/business/service/BusinessProductServiceTest.java, src/test/java/umc/stockoneqback/common/ControllerTest.java, src/test/java/umc/stockoneqback/friend/service/FriendProductServiceTest.java, src/test/java/umc/stockoneqback/product/service/ProductOthersServiceTest.java, src/test/java/umc/stockoneqback/product/service/ProductServiceTest.java
- Friend/Business ProductService 테스트 코드 작성
- Friend/Business ProductService 테스트 코드 작성
- 기존 코드의 일부 오탈자 수정
- #82 에 할 일로 남겼던 테스트 코드 작성입니다.
- #82 @chaeeerish 말씀대로 다음부터는 API 개발하면서 모든 테스트 코드를 작성한 뒤에 한번에 올리겠습니다!😅
Closes #83
=> [Test] Friend/Business ProductService 테스트 코드를 작성한다

src/docs/asciidoc/board-list.adoc, src/main/java/umc/stockoneqback/board/controller/BoardListApiController.java, src/main/java/umc/stockoneqback/board/controller/dto/SelectedMyBoardRequest.java, src/main/java/umc/stockoneqback/board/domain/SearchType.java, src/main/java/umc/stockoneqback/board/infra/query/BoardListQueryRepository.java, src/main/java/umc/stockoneqback/board/infra/query/BoardListQueryRepositoryImpl.java, src/main/java/umc/stockoneqback/board/service/BoardListService.java, src/main/java/umc/stockoneqback/user/exception/UserErrorCode.java, src/main/resources/application.yml, src/test/java/umc/stockoneqback/board/controller/BoardListApiControllerTest.java, src/test/java/umc/stockoneqback/board/infra/query/BoardListQueryRepositoryImplTest.java, src/test/java/umc/stockoneqback/board/service/BoardListServiceTest.java
게시판 내가 쓴 글 보기 API를 구현한다
- 내가 쓴 글 목록 조회 api 추가
- 내가 쓴 글 삭제 api 추가
- 테스트 코드 추가 및 board-list.adoc 수정
- application.yml 수정
노션 secret.yml에 rds 관련 변수 작성해두었습니다
Closes #88
=> [Feat] 게시판 내가 쓴 글 보기 API를 구현한다

src/main/java/umc/stockoneqback/board/controller/dto/BoardListResponse.java, src/main/java/umc/stockoneqback/board/service/BoardListService.java, src/test/java/umc/stockoneqback/board/controller/BoardListApiControllerTest.java
BoardList Dto를 수정한다
- response dto에 전체 게시글 수 추가
Closes #101
=> [Api] BoardList Dto를 수정한다

src/main/java/umc/stockoneqback/board/controller/BoardApiController.java, src/main/java/umc/stockoneqback/board/controller/dto/BoardResponse.java, src/main/java/umc/stockoneqback/board/domain/Board.java, src/main/java/umc/stockoneqback/board/service/BoardService.java, src/test/java/umc/stockoneqback/board/controller/BoardApiControllerTest.java, src/test/java/umc/stockoneqback/board/domain/BoardTest.java, src/test/java/umc/stockoneqback/board/service/BoardServiceTest.java, src/test/java/umc/stockoneqback/fixture/BoardFixture.java
Board에서 file 컬럼을 제거한다
* Board에서 file 컬럼 제거
* Board
* BoardRequest
* BoardResponse
* BoardService
* BoardApiController
* 테스트 코드 수정
* BoardTest
* BoardFixture
* BoardServiceTest
* BoardApiControllerTest
Closes #103
=> [Feat] Board에서 file 컬럼을 제거한다

src/docs/asciidoc/board.adoc, src/main/java/umc/stockoneqback/board/controller/BoardApiController.java, src/main/java/umc/stockoneqback/board/controller/dto/BoardResponse.java, src/main/java/umc/stockoneqback/board/service/BoardService.java, src/test/java/umc/stockoneqback/board/controller/BoardApiControllerTest.java, src/test/java/umc/stockoneqback/board/service/BoardServiceTest.java
커뮤니티 게시글 세부 조회 항목을 수정한다
* 커뮤니티 게시글 세부 조회 항목 수정
* writer -> writerId로 명확한 명칭으로 수정 
* writerName 추가
* BoardResonse 수정에 따른 관련 부분 수정
* 불필요한 게시글 delete 메서드 제거
* board.docs
Closes #111
=> [Feat] 커뮤니티 게시글 세부 조회 항목을 수정한다

src/test/java/umc/stockoneqback/common/EmbeddedRedisConfig.java, src/test/java/umc/stockoneqback/common/RedisCleaner.java, src/test/java/umc/stockoneqback/product/config/PassProductBatchConfigTest.java
- 머지 이후 Redis 관련 테스트코드 오류를 해결한다
- 테스트코드 실행 시마다 Redis 초기화할 수 있도록 테스트코드 설정 추가
- 어제 머지한 코드를 테스트 실행했을 때 PassProductBatchConfigTest에서 Redis 초기화가 되지 않으면서 오류가 발생하는 현상을 확인하여 테스트코드 내에서 Redis를 초기화할 수 있도록 설정을 추가했습니다😃
Closes #122
=> [Fix] 머지 이후 Redis 관련 테스트코드 오류를 해결한다

src/main/java/umc/stockoneqback/board/domain/Board.java, src/main/java/umc/stockoneqback/board/service/BoardService.java, src/test/java/umc/stockoneqback/board/service/BoardServiceTest.java
커뮤니티 게시글 조회수 증가 기능을 구현한다
* 커뮤니티 게시글 조회수 증가 기능 구현
* Board에 updateHit() 추가
* BoardService에서 상세 조회시 updateHit() 실행  
* 테스트 코드
* BoardServiceTest에 상세 조회 테스트 작성 
BoardServiceTest에 상세 조회 테스트가 빠져있어서 이 부분 추가하면서 게시글 조회수가 +1되어서 리턴되는지 테스트했습니다.
Closes #39
=> [Feat] 커뮤니티 게시글 조회수 증가 기능을 구현한다

src/main/java/umc/stockoneqback/user/infra/query/UserFindQueryRepositoryImpl.java, src/test/java/umc/stockoneqback/common/ServiceTest.java, src/test/java/umc/stockoneqback/share/infra/query/ShareListQueryRepositoryImplTest.java
- 머지 이후 UserFindQueryRepository 쿼리 오류를 해결한다
- 머지 이후 UserFindQueryRepository 쿼리 오류를 해결한다
- UserFind 이전의 불필요한 쿼리가 남아있어 삭제했습니다.
- 테스트 코드에서 Share 관련해 Fixture와 상충되는 부분이 있어 일부 수정했습니다.
Closes #129
=> [Fix] 머지 이후 UserFindQueryRepository 쿼리 오류를 해결한다

src/main/java/umc/stockoneqback/comment/domain/CommentRepository.java
- CommentRepository 쿼리 오류를 해결한다
- 쿼리 오타 수정
Closes #132
=> [Fix] CommentRepository 쿼리 오류를 해결한다

src/main/java/umc/stockoneqback/reply/domain/ReplyRepository.java, src/test/java/umc/stockoneqback/comment/controller/CommentListApiControllerTest.java, src/test/java/umc/stockoneqback/reply/service/ReplyListServiceTest.java
ReplyRepository 쿼리 오류를 해결한다
* ReplyRepository 쿼리 오류를 해결한다
Closes #134
=> [Feat] ReplyRepository 쿼리 오류를 해결한다

src/main/java/umc/stockoneqback/share/exception/ShareErrorCode.java
merge 이후 ShareErrorCode 오류를 해결한다
ShareErrorCode 쉼표 추가
Closes #137
=> [Fix] merge 이후 ShareErrorCode 오류를 해결한다

src/main/java/umc/stockoneqback/reply/domain/ReplyRepository.java, src/test/java/umc/stockoneqback/comment/controller/CommentListApiControllerTest.java, src/test/java/umc/stockoneqback/reply/service/ReplyListServiceTest.java
커뮤니티 게시글 세부 조회 항목에 게시글 좋아요 여부를 추가한다
* 커뮤니티 게시글 세부 조회 항목에 게시글 좋아요 여부를 추가한다
Closes #131
=> [Feat] 커뮤니티 게시글 세부 조회 항목에 게시글 좋아요 여부를 추가한다

src/docs/asciidoc/board.adoc, src/main/java/umc/stockoneqback/board/controller/dto/BoardResponse.java, src/main/java/umc/stockoneqback/board/service/BoardService.java, src/main/java/umc/stockoneqback/reply/domain/ReplyRepository.java, src/test/java/umc/stockoneqback/board/controller/BoardApiControllerTest.java, src/test/java/umc/stockoneqback/comment/controller/CommentListApiControllerTest.java, src/test/java/umc/stockoneqback/reply/service/ReplyListServiceTest.java
커뮤니티 게시글 세부 조회 항목에 게시글 좋아요 여부 관련 누락된 파일을 추가한다 
커뮤니티 게시글 세부 조회 항목에 게시글 좋아요 여부 관련 누락된 파일을 추가한다 
Closes #146
=> [Feat] 커뮤니티 게시글 세부 조회 항목에 게시글 좋아요 여부 관련 누락된 파일을 추가한다 

src/docs/asciidoc/board.adoc, src/main/java/umc/stockoneqback/board/controller/BoardApiController.java, src/main/java/umc/stockoneqback/board/service/BoardService.java, src/test/java/umc/stockoneqback/board/controller/BoardApiControllerTest.java, src/test/java/umc/stockoneqback/board/service/BoardServiceTest.java
조회수 증가 API를 구현한다
* 게시글 상세조회 API에서 조회수 증가 메서드 제거
* 조회수 증가 API 구현  
* BoardService
* BoardApiController 
* 테스트 코드
* BoardServiceTest
* BoardApiControllerTest 
Closes #148
=> [Feat] 조회수 증가 API를 구현한다

src/docs/asciidoc/business-product.adoc, src/docs/asciidoc/friend-product.adoc, src/docs/asciidoc/product.adoc, src/main/java/umc/stockoneqback/business/controller/BusinessProductApiController.java, src/main/java/umc/stockoneqback/business/service/BusinessProductService.java, src/main/java/umc/stockoneqback/friend/controller/FriendProductApiController.java, src/main/java/umc/stockoneqback/friend/service/FriendProductService.java, src/main/java/umc/stockoneqback/product/controller/ProductApiController.java, src/main/java/umc/stockoneqback/product/domain/ProductRepository.java, src/main/java/umc/stockoneqback/product/domain/SearchCondition.java, src/main/java/umc/stockoneqback/product/exception/ProductErrorCode.java, src/main/java/umc/stockoneqback/product/infra/query/FindProductQueryRepository.java, src/main/java/umc/stockoneqback/product/infra/query/FindProductQueryRepositoryImpl.java, src/main/java/umc/stockoneqback/product/infra/query/dto/FindProductPage.java, src/main/java/umc/stockoneqback/product/service/ProductOthersService.java, src/main/java/umc/stockoneqback/product/service/ProductService.java, src/test/java/umc/stockoneqback/business/controller/BusinessProductApiControllerTest.java, src/test/java/umc/stockoneqback/business/service/BusinessProductServiceTest.java, src/test/java/umc/stockoneqback/friend/controller/FriendProductApiControllerTest.java, src/test/java/umc/stockoneqback/friend/service/FriendProductServiceTest.java, src/test/java/umc/stockoneqback/product/controller/ProductApiControllerTest.java, src/test/java/umc/stockoneqback/product/domain/ProductRepositoryTest.java, src/test/java/umc/stockoneqback/product/service/ProductOthersServiceTest.java, src/test/java/umc/stockoneqback/product/service/ProductServiceTest.java
- Product 로직을 리팩토링한다
- 쿼리를 native query에서 Querydsl로 변경하면서 유연성을 늘린다
- 기존에 불필요하게 나눴던 탐색 조건별 페이징을 Querydsl을 활용해 하나의 공통 쿼리 안에서 동작할 수 있도록 변경
- 로컬 테스트는 완료했으며, Product 관련 API가 프론트 세 분 모두 사용되는 부분이라서 부득이하게 테스트 코드를 모두 작성하기 전에 올립니다. 누락된 Service 및 Repository 테스트 코드를 이어서 수정하도록 하겠습니다😅
Closes #145
=> [Refactor] Product 로직을 리팩토링한다

src/main/java/umc/stockoneqback/auth/service/AuthService.java, src/main/java/umc/stockoneqback/auth/service/dto/response/LoginResponse.java, src/test/java/umc/stockoneqback/auth/controller/AuthApiControllerTest.java, src/test/java/umc/stockoneqback/auth/service/AuthServiceTest.java
로그인 응답을 수정한다
- LoginResponse에 사용자 이름 추가
Closes #152
=> [Feat] 로그인 응답을 수정한다

.gitignore, src/main/java/umc/stockoneqback/global/config/FcmConfig.java
- 환경변수 설정을 위해 Firebase의 설정 파일 형식을 json에서 yml로 변경한다
- Firebase의 설정 파일 형식 변경 및 gitignore 수정
- Fcm config 에서 yml 형식을 json 형식으로 입력받을 수 있도록 형변환하는 로직 추가
Closes #154
=> [Chore] Firebase의 설정 파일 형식을 변경한다

.gitignore, src/main/java/umc/stockoneqback/global/config/FcmConfig.java, src/main/resources/application.yml
- 환경변수 문제 해결
- Firebase 관련 환경변수 문제 해결
Closes #154
=> [Fix] 환경변수 문제 해결

src/main/java/umc/stockoneqback/business/controller/BusinessListApiController.java, src/main/java/umc/stockoneqback/business/domain/BusinessRepository.java, src/main/java/umc/stockoneqback/business/infra/query/BusinessListQueryRepository.java, src/main/java/umc/stockoneqback/business/infra/query/BusinessListQueryRepositoryImpl.java, src/main/java/umc/stockoneqback/business/infra/query/dto/BusinessList.java, src/main/java/umc/stockoneqback/business/service/BusinessListService.java, src/main/java/umc/stockoneqback/business/service/dto/BusinessListResponse.java, src/test/java/umc/stockoneqback/business/controller/BusinessListApiControllerTest.java, src/test/java/umc/stockoneqback/business/infra/query/BusinessListQueryRepositoryImplTest.java, src/test/java/umc/stockoneqback/business/service/BusinessListServiceTest.java, src/test/java/umc/stockoneqback/common/ControllerTest.java
커넥트 Business 목록 api를 구현한다
- 나와 연결된 슈퍼바이저 목록 & 검색 api 구현
- 나와 연결된 점주 목록 api 구현
- 테스트코드 작성
Closes #157
=> [Feat] 커넥트 Business 목록 api를 구현한다

src/main/java/umc/stockoneqback/product/service/ProductFindService.java, src/test/java/umc/stockoneqback/product/controller/ProductFindApiControllerTest.java, src/test/java/umc/stockoneqback/product/service/ProductFindServiceTest.java
- 머지 후 충돌을 해결한다
- ProductFindService 및 테스트
Closes #165
=> [Fix] 머지 후 충돌을 해결한다
